version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gistex-translator-backend
    restart: always
    network_mode: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/opt/conda/lib/python3.10/site-packages/nvidia/cublas/lib:/opt/conda/lib/python3.10/site-packages/nvidia/cudnn/lib
    volumes:
      - ./backend/glossary.json:/app/glossary.json
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gistex-translator-frontend
    restart: always
    network_mode: "host"
    depends_on:
      - backend

volumes:
  hf_cache:
    name: gistex_hf_cache
